version: '3'

services:
  db_ricettario:
    container_name: 'db_ricettario'
    image: 'postgres:14.2-alpine'
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./database/ricettario:/var/lib/postgresql/data/

  be_ricettario:
    entrypoint: /bin/sh './scripts/be-node-dev.sh'
    env_file:
      - .env
    ports:
      - '4000:4000'
    depends_on:
      - db_ricettario
    links:
      - db_ricettario

  be_ricettario_test:
    container_name: 'be_ricettario_test'
    command: sh -c "echo 'Test container ready' && tail -f /dev/null"
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - db_ricettario
    links:
      - db_ricettario
    env_file:
      - .env
    volumes:
      - .:/app/
      - /app/node_modules
